Repository sligtly-used-but-mostly-confused/projectVFighter, pull requests merged in 2018-09, with the labels that each got.

#18 Throwing mechanic
  VFighter/Assets/Plugins/Input/Examples/Configuration/gamepad.asset
  VFighter/Assets/Plugins/Input/x86/XInputDotNetPure.dll.meta
  VFighter/Assets/Plugins/Input/x86/XInputInterface.dll.meta
  VFighter/Assets/Plugins/Input/x86_64/XInputDotNetPure.dll.meta
  VFighter/Assets/Plugins/Input/x86_64/XInputInterface.dll.meta
  VFighter/Assets/Plugins/ML-Agents/Scripts/Academy.cs
  VFighter/Assets/Prefabs/player.prefab
  VFighter/Assets/Resources/Wall.physicsMaterial2D
  VFighter/Assets/Resources/Wall.physicsMaterial2D.meta
  VFighter/Assets/Scenes/AITraining.unity
  VFighter/Assets/Scenes/Main.unity
  VFighter/Assets/Scripts/AIStuff/AIAgent.cs
  VFighter/Assets/Scripts/GamepadPlayerController.cs
  VFighter/Assets/Scripts/GravityGunProjectileController.cs
  VFighter/Assets/Scripts/GravityObjectRigidBody.cs
  VFighter/Assets/Scripts/KeyboardPlayerController.cs
  VFighter/Assets/Scripts/PlayerController.cs
  VFighter/Assets/Scripts/ScriptableObjectUtility.cs
  VFighter/Assets/Scripts/ScriptableObjectUtility.cs.meta
  VFighter/ProjectSettings/EditorBuildSettings.asset
  VFighter/ProjectSettings/GraphicsSettings.asset
  VFighter/ProjectSettings/UnityConnectSettings.asset
  VFighter/UnitySDK.log
Labels: mechanics, review

#30 fixed inputs
  VFighter/Assets/Plugins/Input/Examples/Configuration/MappedAxis.cs
  VFighter/Assets/Plugins/Input/MappedInput/Scripts/core/InputDevice.cs
  VFighter/Assets/Plugins/Input/MappedInput/Scripts/devices/GamepadInputDevice.cs
  VFighter/Assets/Plugins/Input/MappedInput/Scripts/devices/KeyboardMouseInputDevice.cs
  VFighter/Assets/Scripts/GamepadPlayerController.cs
  VFighter/Assets/Scripts/KeyboardPlayerController.cs
  VFighter/Assets/StreamingAssets.meta
Labels: review

#31 Reset level after finish
  VFighter/Assets/Plugins/Input/Examples/Configuration/gamepad.asset
  VFighter/Assets/Plugins/Input/GamepadInput/Scripts/GamepadInput.cs
  VFighter/Assets/Plugins/Input/MappedInput/Scripts/core/MappedInput.cs
  VFighter/Assets/Plugins/Input/MappedInput/Scripts/devices/KeyboardMouseInputDevice.cs
  VFighter/Assets/Resources/GravityObject.physicsMaterial2D
  VFighter/Assets/Resources/GravityObject.physicsMaterial2D.meta
  VFighter/Assets/Scenes/Main.unity
  VFighter/Assets/Scripts/GameManager.cs
  VFighter/Assets/Scripts/GravityObjectRigidBody.cs
  VFighter/Assets/Scripts/KeyboardPlayerController.cs
  VFighter/Assets/Scripts/PlayerCameraController.cs
  VFighter/Assets/Scripts/PlayerController.cs
  VFighter/ProjectSettings/EditorBuildSettings.asset
Labels: in progress

#29 added spring level
  VFighter/Assets/Plugins/Input/MappedInput/Scripts/core/InputDevice.cs
  VFighter/Assets/Plugins/Input/MappedInput/Scripts/core/MappedInput.cs
  VFighter/Assets/Prefabs/GamepadPlayer.prefab
  VFighter/Assets/Prefabs/GamepadPlayer.prefab.meta
  VFighter/Assets/Prefabs/KeyboardMousePlayer.prefab
  VFighter/Assets/Prefabs/KeyboardMousePlayer.prefab.meta
  VFighter/Assets/Prefabs/SpringPlatform.prefab
  VFighter/Assets/Prefabs/SpringPlatform.prefab.meta
  VFighter/Assets/Scenes/Main.unity
  VFighter/Assets/Scenes/SpringLevel.unity
  VFighter/Assets/Scenes/SpringLevel.unity.meta
  VFighter/Assets/Scripts/GameManager.cs
  VFighter/Assets/Scripts/GamepadPlayerController.cs
  VFighter/Assets/Scripts/GravityGunProjectileController.cs
  VFighter/Assets/Scripts/GravityObjectRigidBody.cs
  VFighter/Assets/Scripts/PlayerController.cs
  VFighter/ProjectSettings/EditorBuildSettings.asset
Labels: review

#25 Gravity zones2
  VFighter/Assets/ForceZoneController.cs
  VFighter/Assets/ForceZoneController.cs.meta
  VFighter/Assets/Prefabs/Effect Zones.meta
  VFighter/Assets/Prefabs/Effect Zones/ForceZone.prefab
  VFighter/Assets/Prefabs/Effect Zones/ForceZone.prefab.meta
  VFighter/Assets/SpeedZoneController.cs
  VFighter/Assets/SpeedZoneController.cs.meta
Labels: review

#47 Addcolorcordination
  VFighter/Assets/Material/Blue.mat
  VFighter/Assets/Material/Blue.mat.meta
  VFighter/Assets/Material/Green.mat
  VFighter/Assets/Material/Green.mat.meta
  VFighter/Assets/Material/Red.mat
  VFighter/Assets/Material/Red.mat.meta
  VFighter/Assets/Prefabs/GamepadPlayer.prefab
  VFighter/Assets/Prefabs/Gravity Pulse.prefab
  VFighter/Assets/Prefabs/GravityObject.prefab
  VFighter/Assets/Scenes/SpringLevel.unity
  VFighter/Assets/Scripts/PlayerController.cs
Labels: mechanics, review

#51 made left trigger jump
  VFighter/Assets/Material/Green.mat
  VFighter/Assets/Plugins/Input/Examples/Configuration/MappedAxis.cs
  VFighter/Assets/Plugins/Input/Examples/Configuration/gamepad.asset
  VFighter/Assets/Scenes/SpringLevel.unity
  VFighter/Assets/Scripts/GamepadPlayerController.cs
Labels: in progress

#54 saving scene
  VFighter/Assets/Material/Green.mat
  VFighter/Assets/Plugins/Input/Examples/Configuration/gamepad.asset
  VFighter/Assets/Scenes/SpringLevel.unity
Labels: review

#56 did the thing
  VFighter/Assets/Scripts/GravityGunProjectileController.cs
Labels: review

#60 Changeskybox
  VFighter/Assets/Material/Green.mat
  VFighter/Assets/Material/Sphere.mat
  VFighter/Assets/Scenes/SpringLevel.unity
Labels: review

#62 updated materials
  VFighter/Assets/Material/Blue.mat
  VFighter/Assets/Material/Box.mat
  VFighter/Assets/Material/Green.mat
  VFighter/Assets/Material/Red.mat
  VFighter/Assets/Scenes/SpringLevel.unity
Labels: review

#63 Shader outline
  .DS_Store
  VFighter/.DS_Store
  VFighter/Assets/.DS_Store
  VFighter/Assets/Material/Box.mat
  VFighter/Assets/Material/Sphere.mat
  VFighter/Assets/Shaders/Glow.shader
  VFighter/Assets/StreamingAssets.meta
Labels: review

#64 Updated Colors
  VFighter/Assets/Material/Blue.mat
  VFighter/Assets/Material/Box.mat
  VFighter/Assets/Material/Green.mat
  VFighter/Assets/Material/Red.mat
  VFighter/Assets/Material/Wall.mat
  VFighter/Assets/Scenes/SpringLevel.unity
Labels: review

#65 added stuff
  .DS_Store
  VFighter/.DS_Store
  VFighter/Assets/.DS_Store
  VFighter/Assets/Material/Emissive Blue.mat
  VFighter/Assets/Material/Emissive Blue.mat.meta
  VFighter/Assets/Material/Emissive Green.mat
  VFighter/Assets/Material/Emissive Green.mat.meta
  VFighter/Assets/Material/Emissive Red.mat
  VFighter/Assets/Material/Emissive Red.mat.meta
  VFighter/Assets/Material/Emissive White.mat
  VFighter/Assets/Material/Emissive White.mat.meta
  VFighter/Assets/Scenes/ShaderTest.unity
Labels: review

#70 Created a Spikes Prefab
  VFighter/Assets/Prefabs/Spikes.prefab
  VFighter/Assets/Prefabs/Spikes.prefab.meta
  VFighter/Assets/SpikesController.cs
  VFighter/Assets/SpikesController.cs.meta
Labels: review

#71 Pinball level
  VFighter/Assets/Prefabs/GamepadPlayer.prefab
  VFighter/Assets/Resources/Bumper.physicsMaterial2D
  VFighter/Assets/Resources/Bumper.physicsMaterial2D.meta
  VFighter/Assets/Resources/Player.physicsMaterial2D
  VFighter/Assets/Resources/Player.physicsMaterial2D.meta
  VFighter/Assets/Scenes/PinBallLevel.unity
  VFighter/Assets/Scenes/PinBallLevel.unity.meta
  VFighter/Assets/Scenes/SpringLevel.unity
  VFighter/Assets/Scripts/GameManager.cs
  VFighter/Assets/Scripts/GravityGunProjectileController.cs
  VFighter/Assets/Scripts/GravityObjectRigidBody.cs
  VFighter/Assets/Scripts/PlayerController.cs
Labels: review

#74 added player management stuff
  VFighter/Assets/ForceZoneController.cs
  VFighter/Assets/Prefabs/Effect Zones/SpeedZone.prefab
  VFighter/Assets/Prefabs/GamepadPlayer.prefab
  VFighter/Assets/Prefabs/Gravity Pulse.prefab
  VFighter/Assets/Prefabs/PlatformSpawnPosition.prefab
  VFighter/Assets/Prefabs/PlatformSpawnPosition.prefab.meta
  VFighter/Assets/Prefabs/Spikes.prefab
  VFighter/Assets/Scenes/LevelSelect.unity
  VFighter/Assets/Scenes/LevelSelect.unity.meta
  VFighter/Assets/Scenes/SpringLevel.unity
  VFighter/Assets/Scripts/AIStuff/AIAgent.cs
  VFighter/Assets/Scripts/GameManager.cs
  VFighter/Assets/Scripts/GamepadPlayerController.cs
  VFighter/Assets/Scripts/GravityObjectRigidBody.cs
  VFighter/Assets/Scripts/LevelManager.cs
  VFighter/Assets/Scripts/ObjectSpawnPosition.cs
  VFighter/Assets/Scripts/ObjectSpawnPosition.cs.meta
  VFighter/Assets/Scripts/Player.cs
  VFighter/Assets/Scripts/Player.cs.meta
  VFighter/Assets/Scripts/PlayerController.cs
  VFighter/Assets/Scripts/PlayerManager.cs
  VFighter/Assets/Scripts/PlayerManager.cs.meta
  VFighter/Assets/Scripts/PlayerSpawnPosition.cs
  VFighter/Assets/Scripts/PlayerSpawnPosition.cs.meta
  VFighter/Assets/Scripts/SpawnPosition.cs
  VFighter/Assets/Scripts/SpawnPosition.cs.meta
  VFighter/Assets/SpeedZoneController.cs
  VFighter/Assets/TeleportZoneController.cs
  VFighter/ProjectSettings/EditorBuildSettings.asset
  VFighter/ProjectSettings/TagManager.asset
Labels: review

#77 did some polishing
  VFighter/Assets/Scenes/SpringLevel.unity
  VFighter/Assets/Scripts/AIStuff.meta
  VFighter/Assets/Scripts/ControllableGravityObjectRigidBody.cs
  VFighter/Assets/Scripts/ControllableGravityObjectRigidBody.cs.meta
  VFighter/Assets/Scripts/GamepadPlayerController.cs
  VFighter/Assets/Scripts/GravityGunProjectileController.cs
  VFighter/Assets/Scripts/GravityObjectRigidBody.cs
  VFighter/Assets/Scripts/ObjectSpawnPosition.cs
Labels: review

#90 added some setupstuff
  VFighter/Assets/Scenes/ControllerSelect.unity
  VFighter/ProjectSettings/EditorBuildSettings.asset
Labels: review

#91 added gravity to the player spawn
  VFighter/Assets/Scenes/ControllerSelect.unity
  VFighter/Assets/Scripts/PlayerControllers/PlayerController.cs
  VFighter/ProjectSettings/Physics2DSettings.asset
  VFighter/ProjectSettings/TagManager.asset
Labels: review

#92 Making walking into other players not kill
  VFighter/Assets/Prefabs/GamepadPlayer.prefab
  VFighter/Assets/Scenes/ControllerSelect.unity
  VFighter/Assets/Scripts/GravityObjectRigidBody.cs
  VFighter/Assets/Scripts/LevelManager.cs
  VFighter/Assets/Scripts/PlayerControllers/PlayerController.cs
Labels: review

#94 did the thing
  VFighter/Assets/Scripts/GravityGunProjectileController.cs
Labels: review

#96 added block
  VFighter/Assets/Prefabs/TronBlock.prefab
  VFighter/Assets/Prefabs/TronBlock.prefab.meta
  VFighter/Assets/Prefabs/TronBlockTail.prefab
  VFighter/Assets/Prefabs/TronBlockTail.prefab.meta
  VFighter/Assets/Scenes/SpringLevel.unity
  VFighter/Assets/Scripts/GameManager.cs
  VFighter/Assets/Scripts/Player.cs
  VFighter/Assets/Scripts/PlayerControllers/GamepadPlayerController.cs
  VFighter/Assets/Scripts/PlayerControllers/KeyboardPlayerController.cs
  VFighter/Assets/Scripts/TronBlock.cs
  VFighter/Assets/Scripts/TronBlock.cs.meta
  VFighter/ProjectSettings/Physics2DSettings.asset
  VFighter/ProjectSettings/TagManager.asset
Labels: review

#100 made base scene
  VFighter/Assets/Prefabs/KeyboardPlayer.prefab
  VFighter/Assets/Scenes/AdvancedLevels.meta
  VFighter/Assets/Scenes/AdvancedLevels/PinBallLevel.unity
  VFighter/Assets/Scenes/AdvancedLevels/PinBallLevel.unity.meta
  VFighter/Assets/Scenes/AdvancedLevels/SpringLevel.unity
  VFighter/Assets/Scenes/AdvancedLevels/SpringLevel.unity.meta
  VFighter/Assets/Scenes/BaseLevel.unity
  VFighter/Assets/Scenes/BaseLevel.unity.meta
  VFighter/Assets/StreamingAssets.meta
Labels: review

#101 added easy level
  VFighter/Assets/CountDownTimer.cs
  VFighter/Assets/CountDownTimer.cs.meta
  VFighter/Assets/Prefabs/CountDown.prefab
  VFighter/Assets/Prefabs/CountDown.prefab.meta
  VFighter/Assets/Prefabs/PlatformSpawnPosition.prefab
  VFighter/Assets/Prefabs/Spawners.meta
  VFighter/Assets/Prefabs/Spawners/ForceZoneSpawnPosition.prefab
  VFighter/Assets/Prefabs/Spawners/ForceZoneSpawnPosition.prefab.meta
  VFighter/Assets/Prefabs/Spawners/PlatformSpawnPosition.prefab
  VFighter/Assets/Prefabs/Spawners/PlatformSpawnPosition.prefab.meta
  VFighter/Assets/Prefabs/Spawners/SpikeSpawnPosition.prefab
  VFighter/Assets/Prefabs/Spawners/SpikeSpawnPosition.prefab.meta
  VFighter/Assets/Prefabs/Spawners/TeleportSpawnPosition.prefab
  VFighter/Assets/Prefabs/Spawners/TeleportSpawnPosition.prefab.meta
  VFighter/Assets/Prefabs/Spawners/Tron Block Spawn Position.prefab
  VFighter/Assets/Prefabs/Spawners/Tron Block Spawn Position.prefab.meta
  VFighter/Assets/Scenes/AdvancedLevels/EasyLevel.unity
  VFighter/Assets/Scenes/AdvancedLevels/EasyLevel.unity.meta
  VFighter/Assets/Scenes/AdvancedLevels/SpringLevel.unity
  VFighter/Assets/Scenes/BaseLevel.unity
  VFighter/Assets/Scripts/GravityObjectRigidBody.cs
Labels: review

#102 Add gravity scaling
  VFighter/Assets/CountDownTimer.cs
  VFighter/Assets/Prefabs/KeyboardPlayer.prefab
  VFighter/Assets/Prefabs/Spawners/PlatformSpawnPosition.prefab
  VFighter/Assets/Scenes/AdvancedLevels/EasyLevel.unity
  VFighter/Assets/Scenes/AdvancedLevels/SpringLevel.unity
  VFighter/Assets/Scripts/ControllerSelectManager.cs
  VFighter/Assets/Scripts/LevelManager.cs
  VFighter/ProjectSettings/EditorBuildSettings.asset
Labels: review
